name: Update YouTube Title

on:
  schedule:
    - cron: "*/10 * * * *"  # setiap 10 menit
  workflow_dispatch:        # bisa juga dijalankan manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node updateTitle.js
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
